---
- hosts: all
  connection: ssh
  tasks:
    - name: installing multiple tsaks
      yum: name='{{item}}' state=present
      with_items:
        - tree
        - python-pip
        - java-1.8.0-openjdk
        - docker
      notify: restart docker
  handlers:
    - name: restart docker 
      service: name=docker state=restarted
